baseURL = "https://medvedku.github.io/SHM_SA/"
languageCode = 'en-us'
title = "SHM Data"
theme = "book"

[params]
  BookSection = "*"
  BookRepo = "https://github.com/Medvedku/SHM_SA"
  BookTheme = "dark"
  BookToC = false
  BookMenuBundle = "content"
  BookLogo = "logo.svg"

  
  # Custom CSS

